//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenBasedWebApi.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string MethodName { get; set; }
        public string Data { get; set; }
        public int LogTypeID { get; set; }
        public bool IsError { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
