//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenBasedWebApi.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Texts
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Release_date { get; set; }
        public System.Guid UserID { get; set; }
        public int TextTypeID { get; set; }
        public bool IsRelease { get; set; }
    
        public virtual TextTypes TextTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
